### ISSUE TITLE
Fatal error in Entity::find on invalid $id

### ISSUE THREAD

**Issue by clund-np** [Penneo/sdk-php#64]
Passing an invalid `$casefile_id` to `CaseFile::find($casefileId)` results in a fatal error.

    Fatal error:  Uncaught Error: Call to a member function getBody() on null in /vendor/penneo/penneo-sdk-php/src/ApiConnector.php:101
    
    Stack trace:
    0 /vendor/penneo/penneo-sdk-php/src/Entity.php(25): Penneo\SDK\ApiConnector::readObject(Object(Penneo\SDK\CaseFile))
    1 /app/lib/penneoApi.php(42): Penneo\SDK\Entity::find(89579861)

**Comment by Malek-Mohamed** [comment]
#62 Duplication.

**Comment by HeadCookie** [comment]
Fixed in [2.4.1](https://github.com/Penneo/sdk-php/releases/tag/2.4.1)

**Comment by clund-np** [comment]
Fatal error still returned for unknown casefile ids `Penneo\SDK\Entity::find(90935381)`

```
Fatal error: Uncaught Penneo\SDK\Exception: Penneo: Could not find the requested Penneo\SDK\CaseFile (id = 90935381) in /vendor/penneo/penneo-sdk-php/src/Entity.php:26
```

**Comment by HeadCookie** [comment]
Hi @clund-np,

As it is now we throw an exception if the entity is not found. You could put it in a try catch to handle that.
